# Generated by Django 6.0.6 on 2026-07-01 23:46

import apps.core.utils.slugs
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_url', models.URLField()),
                ('slug', models.CharField(blank=True, db_index=True, default=apps.core.utils.slugs.generate_slug, max_length=24, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('max_clicks', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shortened_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('browser', models.CharField(blank=True, max_length=64)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('referrer_domain', models.CharField(blank=True, max_length=200)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clicks', to='core.shorturl')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_url', 'created_at'], name='core_click_short_u_6e48d5_idx'), models.Index(fields=['created_at'], name='core_click_created_98e0fc_idx')],
            },
        ),
    ]
